package com.tts.SubscriberList.subscriber;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import org.hibernate.annotations.CreationTimeStamp;
import org.springframework.data.annotation.CreatedDate;

@Entity
public class Subscriber {
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Long id;
	//sets the 'id' as the primary key and allows the 'id' to be generated by the underlying database
	
	private String firstName;
	private String lastName;
	private String userName;
	private Date signedUp;
	
public Subscriber() {
	//non-argument constructor needed for JPA
	
}	
	
public Subscriber(String firstName, String lastName, String userName, Date signedUp) {
	
	this.firstName = firstName;
	this.lastName = lastName;
	this.userName = userName;
	
	@Column
	@CreationTimestamp
	
	this.signedUp = signedUp;
	//allows the date to be generated by the system
	
}

public String getFirstName() {
	return firstName;
}

public void setFirstName(String firstName) {
	this.firstName = firstName;
}

public String getLastName() {
	return lastName;
}

public void setLastName(String lastName) {
	this.lastName = lastName;
}

public String getUserName() {
	return userName;
}

public void setUserName(String userName) {
	this.userName = userName;
}

public Date getSignedUp() {
	return signedUp;
}

public void setSignedUp(Date signedUp) {
	this.signedUp = signedUp;
	
	
}

@Override
public String toString() {
	return "Subscriber [firstName=" + firstName + ", lastName=" + lastName + ", userName=" + userName + ", signedUp="
			+ signedUp + "]";
}

}
